-- =============================================================================
-- DISPARA-ZAP — Estrutura Completa do Banco de Dados
-- Gerado em: 2026-04-01
-- Supabase Project: dispara-zap (yuypedritsizhuegslej)
--
-- INSTRUÇÕES PARA ALUNOS:
-- 1. Crie um novo projeto no Supabase
-- 2. Acesse o SQL Editor
-- 3. Cole e execute este arquivo inteiro
-- 4. Após executar, preencha os valores reais na tabela platform_settings
--    (Seção 6) via SQL Editor ou direto na tabela no Supabase Dashboard
-- =============================================================================


-- =============================================================================
-- SEÇÃO 1 — EXTENSÕES
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp"          WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pgcrypto"            WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_net"              WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_cron"             WITH SCHEMA pg_catalog;
CREATE EXTENSION IF NOT EXISTS "pg_graphql"          WITH SCHEMA graphql;
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements"  WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pg_trgm"             WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "pgmq"                WITH SCHEMA pgmq;
-- Nota: supabase_vault é instalado automaticamente pelo Supabase em projetos novos.
-- Não é necessário criar manualmente — já estará disponível no schema vault.


-- =============================================================================
-- SEÇÃO 2 — TABELAS (em ordem de dependência)
-- =============================================================================

-- --------------------------------------------------------------------
-- 2.1 planos_sistema
-- Tabela de planos disponíveis na plataforma (trial, básico, etc.)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.planos_sistema (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                TEXT NOT NULL UNIQUE,
    nome                TEXT NOT NULL,
    descricao           TEXT,
    valor               NUMERIC NOT NULL DEFAULT 0,
    tipo_periodo        TEXT NOT NULL DEFAULT 'free',
    link_checkout       TEXT NOT NULL DEFAULT '',
    recursos            JSONB NOT NULL DEFAULT '[]'::jsonb,
    ativo               BOOLEAN NOT NULL DEFAULT true,
    destaque            BOOLEAN NOT NULL DEFAULT false,
    ordem_exibicao      INTEGER NOT NULL DEFAULT 1,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    max_grupos          INTEGER,
    max_marketplaces    INTEGER,
    max_disparos_dia    INTEGER,
    max_destinos_grupo  INTEGER,
    periodo_dias        INTEGER,
    valor_mensal_equiv  NUMERIC,

    CONSTRAINT planos_sistema_tipo_periodo_check
        CHECK (tipo_periodo = ANY (ARRAY['free','mensal','trimestral','semestral','anual'])),
    CONSTRAINT planos_sistema_ordem_exibicao_check
        CHECK (ordem_exibicao > 0)
);


-- --------------------------------------------------------------------
-- 2.2 platform_settings
-- Configurações globais da plataforma (Evolution API, limites, etc.)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.platform_settings (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL DEFAULT '',
    description TEXT,
    updated_at  TIMESTAMPTZ DEFAULT now()
);


-- --------------------------------------------------------------------
-- 2.3 users
-- Perfis de usuários (espelha auth.users do Supabase)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
    id           UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    display_name TEXT,
    avatar_url   TEXT,
    created_at   TIMESTAMPTZ DEFAULT now(),
    updated_at   TIMESTAMPTZ DEFAULT now()
);


-- --------------------------------------------------------------------
-- 2.4 user_plans
-- Plano ativo de cada usuário e contadores de uso
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_plans (
    id                               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                          UUID NOT NULL UNIQUE,
    plan                             TEXT NOT NULL DEFAULT 'free',
    plan_id                          INTEGER NOT NULL,
    plan_started_at                  TIMESTAMPTZ,
    plan_expires_at                  TIMESTAMPTZ,
    daily_dispatch_count             INTEGER DEFAULT 0,
    daily_dispatch_reset_at          DATE DEFAULT CURRENT_DATE,
    payment_provider_customer_id     TEXT,
    payment_provider_subscription_id TEXT,
    created_at                       TIMESTAMPTZ DEFAULT now(),
    updated_at                       TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT user_plans_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT user_plans_plan_id_fkey
        FOREIGN KEY (plan_id) REFERENCES public.planos_sistema(id)
);


-- --------------------------------------------------------------------
-- 2.5 whatsapp_instances
-- Instâncias WhatsApp criadas pelo usuário via Evolution API
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.whatsapp_instances (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL UNIQUE,
    instance_name   TEXT NOT NULL UNIQUE,
    status          TEXT NOT NULL DEFAULT 'disconnected',
    phone_number    TEXT,
    qr_code         TEXT,
    qr_expires_at   TIMESTAMPTZ,
    provider_token   TEXT,
    connected_at    TIMESTAMPTZ,
    disconnected_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT whatsapp_instances_status_check
        CHECK (status = ANY (ARRAY['disconnected','qr_pending','connected','error'])),
    CONSTRAINT whatsapp_instances_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.6 channel_connections
-- Conexões de canal do usuário (WhatsApp, Telegram, etc.)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.channel_connections (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID NOT NULL,
    channel_type     TEXT NOT NULL,
    label            TEXT NOT NULL,
    encrypted_config TEXT NOT NULL,
    is_connected     BOOLEAN DEFAULT false,
    last_status_at   TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT now(),
    updated_at       TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT channel_connections_channel_type_check
        CHECK (channel_type = ANY (ARRAY['whatsapp','telegram'])),
    CONSTRAINT channel_connections_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.7 marketplace_connections
-- Credenciais de acesso do usuário a cada marketplace
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.marketplace_connections (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id               UUID NOT NULL,
    marketplace           TEXT NOT NULL,
    encrypted_credentials TEXT NOT NULL,
    is_valid              BOOLEAN DEFAULT true,
    last_validated_at     TIMESTAMPTZ,
    validation_error      TEXT,
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT marketplace_connections_user_id_marketplace_key
        UNIQUE (user_id, marketplace),
    CONSTRAINT marketplace_connections_marketplace_check
        CHECK (marketplace = ANY (ARRAY['amazon','mercadolivre','shopee','aliexpress','kabum','temu','shein'])),
    CONSTRAINT marketplace_connections_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.8 dispatch_groups
-- Grupos de disparo configurados pelo usuário
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dispatch_groups (
    id                         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                    UUID NOT NULL,
    name                       TEXT NOT NULL,
    icon                       TEXT,
    marketplaces               TEXT[] NOT NULL DEFAULT '{}'::text[],
    categories                 TEXT[] DEFAULT '{}'::text[],
    keywords                   TEXT[] DEFAULT '{}'::text[],
    blocked_keywords           TEXT[] DEFAULT '{}'::text[],
    min_discount               INTEGER DEFAULT 0,
    min_price                  INTEGER,
    max_price                  INTEGER,
    min_sales                  INTEGER DEFAULT 0,
    daily_limit                INTEGER NOT NULL DEFAULT 10,
    messaging_interval_minutes INTEGER NOT NULL DEFAULT 5,
    is_active                  BOOLEAN DEFAULT true,
    schedule_hours             INTEGER[] DEFAULT '{8,12,18}'::integer[],
    template_text              TEXT,
    created_at                 TIMESTAMPTZ DEFAULT now(),
    updated_at                 TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT dispatch_groups_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.9 automation_rules
-- Regras de automação por marketplace (fetch + dispatch)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.automation_rules (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id                 UUID NOT NULL,
    marketplace             TEXT NOT NULL,
    rule_type               TEXT NOT NULL,
    is_active               BOOLEAN DEFAULT false,
    interval_minutes        INTEGER NOT NULL DEFAULT 60,
    start_hour              INTEGER NOT NULL DEFAULT 8,
    end_hour                INTEGER NOT NULL DEFAULT 22,
    last_run_at             TIMESTAMPTZ,
    products_found_today    INTEGER DEFAULT 0,
    products_found_reset_at DATE DEFAULT CURRENT_DATE,
    target_group_ids        UUID[] NOT NULL DEFAULT '{}'::uuid[],
    created_at              TIMESTAMPTZ DEFAULT now(),
    updated_at              TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT automation_rules_user_id_marketplace_rule_type_key
        UNIQUE (user_id, marketplace, rule_type),
    CONSTRAINT automation_rules_marketplace_check
        CHECK (marketplace = ANY (ARRAY['amazon','mercadolivre','shopee','aliexpress','kabum','temu','shein'])),
    CONSTRAINT automation_rules_rule_type_check
        CHECK (rule_type = ANY (ARRAY['fetch','dispatch'])),
    CONSTRAINT automation_rules_start_hour_check
        CHECK ((start_hour >= 0) AND (start_hour <= 23)),
    CONSTRAINT automation_rules_end_hour_check
        CHECK ((end_hour >= 0) AND (end_hour <= 23)),
    CONSTRAINT automation_rules_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.10 offers
-- Ofertas captadas dos marketplaces
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.offers (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID NOT NULL,
    marketplace      TEXT NOT NULL,
    external_id      TEXT NOT NULL,
    title            TEXT NOT NULL,
    current_price    INTEGER NOT NULL,
    original_price   INTEGER,
    discount_percent INTEGER,
    image_url        TEXT,
    product_url      TEXT NOT NULL,
    condition        TEXT,
    installments     TEXT,
    category         TEXT,
    affiliate_link   TEXT,
    fetched_at       TIMESTAMPTZ DEFAULT now(),
    expires_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT offers_user_id_marketplace_external_id_key
        UNIQUE (user_id, marketplace, external_id),
    CONSTRAINT offers_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.11 group_destinations
-- Destinos de disparo dentro de cada grupo (grupos WhatsApp, canais, etc.)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.group_destinations (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id     UUID NOT NULL,
    channel_id   UUID,
    target_id    TEXT NOT NULL,
    target_name  TEXT,
    channel_type TEXT NOT NULL DEFAULT 'whatsapp',
    created_at   TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT group_destinations_group_id_target_id_key
        UNIQUE (group_id, target_id),
    CONSTRAINT group_destinations_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.dispatch_groups(id) ON DELETE CASCADE
);


-- --------------------------------------------------------------------
-- 2.12 dispatch_logs
-- Histórico de disparos realizados
-- offer_id é nullable: quando um offer expira e é deletado, o log é preservado
-- mas offer_id vira NULL (ON DELETE SET NULL).
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dispatch_logs (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id             UUID NOT NULL,
    group_id            UUID NOT NULL,
    offer_id            UUID,  -- nullable: SET NULL quando offer é deletado
    channel_type        TEXT NOT NULL,
    status              TEXT NOT NULL DEFAULT 'pending',
    error_message       TEXT,
    external_message_id TEXT,
    attempt_count       INTEGER DEFAULT 1,
    dispatched_at       TIMESTAMPTZ DEFAULT now(),
    dispatched_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at          TIMESTAMPTZ DEFAULT now(),

    CONSTRAINT dispatch_logs_status_check
        CHECK (status = ANY (ARRAY['pending','sent','delivered','read','failed'])),
    CONSTRAINT dispatch_logs_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT dispatch_logs_group_id_fkey
        FOREIGN KEY (group_id) REFERENCES public.dispatch_groups(id),
    CONSTRAINT dispatch_logs_offer_id_fkey
        FOREIGN KEY (offer_id) REFERENCES public.offers(id) ON DELETE SET NULL
);


-- =============================================================================
-- SEÇÃO 3 — ÍNDICES
-- =============================================================================

-- automation_rules
CREATE INDEX IF NOT EXISTS idx_automation_rules_user
    ON public.automation_rules USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_automation_rules_active
    ON public.automation_rules USING btree (is_active, rule_type)
    WHERE (is_active = true);

-- channel_connections
CREATE INDEX IF NOT EXISTS idx_channel_connections_user
    ON public.channel_connections USING btree (user_id);

-- dispatch_groups
CREATE INDEX IF NOT EXISTS idx_dispatch_groups_user_active
    ON public.dispatch_groups USING btree (user_id)
    WHERE (is_active = true);

-- dispatch_logs
CREATE INDEX IF NOT EXISTS idx_dispatch_logs_user
    ON public.dispatch_logs USING btree (user_id, dispatched_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispatch_logs_group
    ON public.dispatch_logs USING btree (group_id, dispatched_at DESC);
CREATE INDEX IF NOT EXISTS idx_dispatch_logs_group_date
    ON public.dispatch_logs USING btree (group_id, dispatched_date DESC);
CREATE INDEX IF NOT EXISTS idx_dispatch_logs_date
    ON public.dispatch_logs USING btree (dispatched_date, user_id);

-- Índice de deduplicação: evita disparar a mesma oferta no mesmo grupo no mesmo dia
CREATE UNIQUE INDEX IF NOT EXISTS idx_dispatch_dedup
    ON public.dispatch_logs USING btree (group_id, offer_id, dispatched_date)
    WHERE (status = ANY (ARRAY['sent','pending','delivered','read']));

-- marketplace_connections
CREATE INDEX IF NOT EXISTS idx_marketplace_connections_user
    ON public.marketplace_connections USING btree (user_id);

-- offers
-- Cobre a query principal de dispatch: filter por user+marketplace+expires, sort por fetched_at
CREATE INDEX IF NOT EXISTS idx_offers_user_mp_fetched
    ON public.offers USING btree (user_id, marketplace, fetched_at DESC);
-- Cobre filter por expires_at (usado no cleanup e em queries de validade)
CREATE INDEX IF NOT EXISTS idx_offers_expires_at
    ON public.offers USING btree (expires_at);
-- Cobre query completa com expires_at como filtro adicional
CREATE INDEX IF NOT EXISTS idx_offers_user_mp_expires
    ON public.offers USING btree (user_id, marketplace, expires_at DESC);
-- GIN trigram: torna ilike '%keyword%' rápido (grupos com palavras-chave)
CREATE INDEX IF NOT EXISTS idx_offers_title_trgm
    ON public.offers USING GIN (title gin_trgm_ops);
-- Partial index para ofertas ML sem link de afiliado (loop de regeneração)
CREATE INDEX IF NOT EXISTS idx_offers_ml_null_affiliate
    ON public.offers USING btree (user_id, marketplace, fetched_at DESC)
    WHERE (marketplace = 'mercadolivre' AND affiliate_link IS NULL);

-- planos_sistema
CREATE INDEX IF NOT EXISTS idx_planos_sistema_ativos
    ON public.planos_sistema USING btree (ordem_exibicao)
    WHERE (ativo = true);

-- whatsapp_instances
CREATE INDEX IF NOT EXISTS idx_whatsapp_instances_status
    ON public.whatsapp_instances USING btree (status);


-- =============================================================================
-- SEÇÃO 4 — ROW LEVEL SECURITY (RLS)
-- =============================================================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.planos_sistema          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.platform_settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_plans              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_instances      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.channel_connections     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketplace_connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_groups         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.automation_rules        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_destinations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_logs           ENABLE ROW LEVEL SECURITY;

-- ---- planos_sistema ----
CREATE POLICY "Planos visíveis por todos"
    ON public.planos_sistema FOR SELECT
    USING (true);

-- ---- users ----
CREATE POLICY "users_own_profile"
    ON public.users FOR ALL
    USING (id = auth.uid())
    WITH CHECK (id = auth.uid());

-- ---- user_plans ----
CREATE POLICY "users_own_plan"
    ON public.user_plans FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- whatsapp_instances ----
CREATE POLICY "users_own_whatsapp_instance"
    ON public.whatsapp_instances FOR ALL
    USING (user_id = auth.uid());

-- ---- channel_connections ----
CREATE POLICY "users_own_channel_connections"
    ON public.channel_connections FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- marketplace_connections ----
CREATE POLICY "users_own_marketplace_connections"
    ON public.marketplace_connections FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- dispatch_groups ----
CREATE POLICY "users_own_dispatch_groups"
    ON public.dispatch_groups FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- automation_rules ----
CREATE POLICY "Users can manage own automation_rules"
    ON public.automation_rules FOR ALL
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- ---- offers ----
CREATE POLICY "users_own_offers"
    ON public.offers FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- group_destinations ----
CREATE POLICY "users_own_group_destinations"
    ON public.group_destinations FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.dispatch_groups
            WHERE dispatch_groups.id = group_destinations.group_id
              AND dispatch_groups.user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.dispatch_groups
            WHERE dispatch_groups.id = group_destinations.group_id
              AND dispatch_groups.user_id = auth.uid()
        )
    );

-- ---- dispatch_logs ----
CREATE POLICY "users_own_dispatch_logs"
    ON public.dispatch_logs FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

-- ---- platform_settings ----
-- Acesso somente via service_role. Política restritiva para anon/authenticated.
CREATE POLICY "platform_settings_admin_only"
    ON public.platform_settings AS RESTRICTIVE
    TO anon, authenticated
    USING (false);

-- Nota: platform_settings é acessado via service_role (backend / Edge Functions).


-- =============================================================================
-- SEÇÃO 5 — FUNCTIONS & TRIGGERS
-- =============================================================================

-- --------------------------------------------------------------------
-- 5.1 handle_new_user
-- Cria o perfil em public.users ao registrar novo usuário no auth
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
BEGIN
    INSERT INTO public.users (id, display_name)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
    );
    RETURN new;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();


-- --------------------------------------------------------------------
-- 5.2 handle_new_user_plan
-- Cria plano trial (7 dias) ao registrar novo usuário no auth
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user_plan()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = 'public'
AS $$
DECLARE
    trial_plan_id INTEGER;
BEGIN
    SELECT id INTO trial_plan_id
    FROM public.planos_sistema
    WHERE slug = 'trial'
    LIMIT 1;

    INSERT INTO public.user_plans
        (user_id, plan, plan_id, plan_started_at, plan_expires_at)
    VALUES
        (new.id, 'trial', trial_plan_id, now(), now() + INTERVAL '7 days');

    RETURN new;
END;
$$;

CREATE OR REPLACE TRIGGER on_auth_user_created_plan
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user_plan();


-- =============================================================================
-- SEÇÃO 6 — DADOS SEED
-- =============================================================================

-- --------------------------------------------------------------------
-- 6.1 planos_sistema — 7 planos da plataforma
-- --------------------------------------------------------------------
INSERT INTO public.planos_sistema
    (id, slug, nome, descricao, valor, tipo_periodo, link_checkout, recursos,
     ativo, destaque, ordem_exibicao,
     max_grupos, max_marketplaces, max_disparos_dia, max_destinos_grupo, periodo_dias, valor_mensal_equiv)
VALUES
    (
        1, 'trial', 'Teste Gratuito', 'Experimente por 7 dias sem cartão',
        0.00, 'free', '',
        '["1 grupo de disparo","1 marketplace","10 disparos por dia","Acesso completo ao dashboard"]'::jsonb,
        true, false, 1,
        1, 1, 10, 1, 7, NULL
    ),
    (
        2, 'basico', 'Básico', 'Para testar o método',
        39.90, 'mensal', '',
        '["Até 3 Grupos (1 conexão WhatsApp)","Até 3 Marketplaces","50 disparos por dia","Envio Automático de Ofertas","Mensagens em Massa","IA para Copies","Suporte por WhatsApp"]'::jsonb,
        true, false, 2,
        3, 3, 50, 1, 30, NULL
    ),
    (
        5, 'basico_anual', 'Básico Anual', 'Para testar o método — melhor preço',
        297.00, 'anual', '',
        '["Até 3 Grupos (1 conexão WhatsApp)","Até 3 Marketplaces","50 disparos por dia","Envio Automático de Ofertas","Mensagens em Massa","IA para Copies","Suporte por WhatsApp","2 meses grátis vs mensal"]'::jsonb,
        true, false, 3,
        3, 3, 50, 1, 365, 58.25
    ),
    (
        3, 'profissional', 'Profissional', 'Escale suas comissões com automação',
        59.90, 'mensal', '',
        '["Até 10 Grupos (1 conexão WhatsApp)","Até 4 Marketplaces","Disparos ilimitados","Tudo do Básico +","Bot de Boas-Vindas","Rastreamento de Links","Espelhamento de Grupos","Reviews de Produtos com IA","Cupons Mercado Livre","Suporte por WhatsApp"]'::jsonb,
        true, true, 3,
        10, 4, NULL, NULL, 30, NULL
    ),
    (
        4, 'premium', 'Premium', 'Máxima escala com tudo incluso',
        99.90, 'mensal', '',
        '["+de 20 Grupos (1 conexão WhatsApp)","Todos os Marketplaces","Disparos ilimitados","Tudo do Profissional incluso","Landing Page Exclusiva","Instagram Flow","UGC com IA","Reaja e Receba","Acesso antecipado a novidades","Suporte Prioritário"]'::jsonb,
        true, false, 4,
        NULL, 5, NULL, NULL, 30, NULL
    ),
    (
        6, 'profissional_anual', 'Profissional Anual', 'Escale suas comissões — melhor custo-benefício',
        497.00, 'anual', '',
        '["Até 10 Grupos (1 conexão WhatsApp)","Até 4 Marketplaces","Disparos ilimitados","Tudo do Básico +","Bot de Boas-Vindas","Rastreamento de Links","Espelhamento de Grupos","Reviews de Produtos com IA","Cupons Mercado Livre","Suporte por WhatsApp","2 meses grátis vs mensal"]'::jsonb,
        true, true, 5,
        10, 4, NULL, NULL, 365, 83.25
    ),
    (
        7, 'premium_anual', 'Premium Anual', 'Máxima escala — preço de atacado',
        697.00, 'anual', '',
        '["+de 20 Grupos (1 conexão WhatsApp)","Todos os Marketplaces","Disparos ilimitados","Tudo do Profissional incluso","Landing Page Exclusiva","Instagram Flow","UGC com IA","Reaja e Receba","Acesso antecipado a novidades","Suporte Prioritário","2 meses grátis vs mensal"]'::jsonb,
        true, false, 7,
        NULL, 5, NULL, NULL, 365, 108.25
    )
ON CONFLICT (id) DO NOTHING;

SELECT setval('public.planos_sistema_id_seq', (SELECT MAX(id) FROM public.planos_sistema));


-- --------------------------------------------------------------------
-- 6.2 platform_settings — configurações globais
--
-- !! ATENÇÃO !!
-- Substitua os valores abaixo pelas suas credenciais reais.
-- --------------------------------------------------------------------
INSERT INTO public.platform_settings (key, value, description) VALUES
    ('evolution_api_url',         'https://sua-evolution.com',        'URL base da Evolution API'),
    ('evolution_api_key',         'SUA_MASTER_API_KEY_AQUI',        'API Key global da Evolution API'),
    ('evolution_webhook_secret',  'MudeIssoSeQuiserOuDeixeAssim', 'Secret token para validar webhooks'),
    ('instance_prefix',           'rg',          'Prefixo para nomes de instâncias WhatsApp'),
    ('whatsapp_max_daily_messages','100',                          'Limite diário de mensagens por instância'),
    ('whatsapp_min_interval_seconds','30',                         'Intervalo mínimo entre mensagens em segundos')
ON CONFLICT (key) DO NOTHING;


-- =============================================================================
-- SEÇÃO 7 — PGMQ (Filas Assíncronas Nativas)
-- =============================================================================

SELECT pgmq.create('dispatch_jobs');
SELECT pgmq.create('fetch_jobs');

-- Interface RPC do Coordinator (acesso externo via supabaseAdmin)
CREATE OR REPLACE FUNCTION public.dz_enqueue_fetch(job jsonb) RETURNS bigint
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT pgmq.send('fetch_jobs', job);
$$;

CREATE OR REPLACE FUNCTION public.dz_enqueue_dispatch(job jsonb) RETURNS bigint
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT pgmq.send('dispatch_jobs', job);
$$;

CREATE OR REPLACE FUNCTION public.dz_dequeue_dispatch(batch_size integer DEFAULT 10)
RETURNS TABLE(msg_id bigint, read_ct integer, enqueued_at timestamptz, vt timestamptz, message jsonb)
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT msg_id, read_ct, enqueued_at, vt, message
  FROM pgmq.read('dispatch_jobs', 120, batch_size);
$$;

CREATE OR REPLACE FUNCTION public.dz_dequeue_fetch(batch_size integer DEFAULT 5)
RETURNS TABLE(msg_id bigint, read_ct integer, enqueued_at timestamptz, vt timestamptz, message jsonb)
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT msg_id, read_ct, enqueued_at, vt, message
  FROM pgmq.read('fetch_jobs', 300, batch_size);
$$;

CREATE OR REPLACE FUNCTION public.dz_complete_dispatch(job_id bigint) RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT pgmq.delete('dispatch_jobs', job_id);
$$;

CREATE OR REPLACE FUNCTION public.dz_complete_fetch(job_id bigint) RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT pgmq.delete('fetch_jobs', job_id);
$$;

CREATE OR REPLACE FUNCTION public.dz_queue_metrics()
RETURNS TABLE(queue_name text, queue_length bigint, oldest_msg_age_sec integer, total_messages bigint)
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public' AS $$
  SELECT queue_name, queue_length, oldest_msg_age_sec, total_messages
  FROM pgmq.metrics_all();
$$;


-- =============================================================================
-- SEÇÃO 8 — CRON JOBS (pg_cron)
--
-- Substitua a URL e o CRON_SECRET pelos valores do seu projeto antes de executar.
-- CRON_SECRET deve ser o mesmo valor definido em CRON_SECRET no .env da Vercel.
-- =============================================================================

-- Coordinator: enfileira jobs de fetch e dispatch a cada 5 minutos
SELECT cron.schedule(
  'auto-automation-5m',
  '*/5 * * * *',
  $$
    SELECT net.http_post(
      url     := 'https://udlmqdwtisolgutzdylw.supabase.co/functions/v1/automation',
      headers := '{"Authorization": "Bearer 38cf3a475fdae9b063487d494d88aa6f", "Content-Type": "application/json"}'::jsonb,
      body    := '{}'::jsonb
    );
  $$
);

-- Worker: processa jobs das filas a cada 1 minuto (ajustado de 5m para melhor vazão)
SELECT cron.schedule(
  'dz-worker-1m',
  '* * * * *',
  $$ SELECT net.http_post(
        url     := 'https://udlmqdwtisolgutzdylw.supabase.co/functions/v1/worker',
        headers := '{"Authorization": "Bearer 38cf3a475fdae9b063487d494d88aa6f", "Content-Type": "application/json"}'::jsonb,
        body    := '{}'::jsonb
     ) $$
);

-- Cleanup: remove offers expiradas toda hora
-- O intervalo '1 hour' garante que offers em processo de disparo não sejam deletadas prematuramente
SELECT cron.schedule(
  'cleanup-expired-offers',
  '0 * * * *',
  $$ DELETE FROM offers WHERE expires_at < NOW() - INTERVAL '1 hour'; $$
);

-- Reset do contador de disparos diários (3h BRT = 6h UTC)
SELECT cron.schedule(
  'reset-daily-dispatch-count',
  '0 3 * * *',
  $$
    UPDATE public.user_plans
    SET daily_dispatch_count = 0,
        daily_dispatch_reset_at = CURRENT_DATE,
        updated_at = NOW()
    WHERE daily_dispatch_reset_at < CURRENT_DATE;
  $$
);


-- =============================================================================
-- SEÇÃO 9 — EDGE FUNCTIONS (Supabase)
--
-- O projeto usa 2 Edge Functions Deno que são chamadas pelos cron jobs acima.
-- Os arquivos estão em supabase/functions/ no repositório.
--
-- Para deployar as Edge Functions no seu projeto (OBRIGATÓRIO --no-verify-jwt para pg_cron funcionar com CRON_SECRET):
--   supabase functions deploy automation --no-verify-jwt --project-ref udlmqdwtisolgutzdylw
--   supabase functions deploy worker     --no-verify-jwt --project-ref udlmqdwtisolgutzdylw
--
-- Ou pelo Supabase Dashboard → Edge Functions → Deploy from GitHub.
--
-- Funções ativas:
--   - automation  → supabase/functions/automation/index.ts
--     Coordenador: lê automation_rules ativas e enfileira jobs no pgmq (fetch_jobs / dispatch_jobs).
--     Chamada a cada 5 minutos pelo cron 'auto-automation-5m'.
--
--   - worker      → supabase/functions/worker/index.ts
--     Processador: dequeues jobs do pgmq e executa fetch/dispatch nos marketplaces.
--     Chamada a cada 1 minuto pelo cron 'dz-worker-1m'.
--
-- IMPORTANTE: As Edge Functions precisam das seguintes variáveis de ambiente:
--   SUPABASE_URL             (auto-injetado pelo Supabase)
--   SUPABASE_SERVICE_ROLE_KEY (auto-injetado pelo Supabase)
--   CRON_SECRET              (definir em Supabase → Settings → Edge Functions → Secrets)
-- =============================================================================


-- =============================================================================
-- FIM DO SCRIPT
--
-- Próximos passos após executar:
-- 1. Atualize platform_settings com seus valores reais (evolution_api_url, etc.)
-- 2. Execute os cron jobs substituindo udlmqdwtisolgutzdylw e 38cf3a475fdae9b063487d494d88aa6f
--    (use o arquivo disparazap_cron.sql)
-- 3. Configure o projeto no .env.local:
--      NEXT_PUBLIC_SUPABASE_URL=https://SEU_PROJECT_ID.supabase.co
--      NEXT_PUBLIC_SUPABASE_ANON_KEY=SEU_ANON_KEY
--      SUPABASE_SERVICE_ROLE_KEY=SEU_SERVICE_ROLE_KEY
--      CRON_SECRET=SEU_CRON_SECRET
-- 4. Deploy das Edge Functions (seção 9 acima)
-- 5. Teste criando um usuário — os triggers devem criar automaticamente
--    o registro em public.users e um plano trial em public.user_plans
-- =============================================================================
