-- ============================================
-- Table: planos_sistema
-- Define os planos disponíveis na plataforma.
-- Desacoplado de user_plans — user_plans.plan referencia o slug do plano.
-- ============================================

CREATE TABLE public.planos_sistema (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,           -- 'free' | 'pro' (deve bater com user_plans.plan)
  nome                TEXT NOT NULL,                  -- Exibição: 'Gratuito', 'Pro'
  descricao           TEXT,
  valor               NUMERIC(10, 2) NOT NULL DEFAULT 0,
  tipo_periodo        TEXT NOT NULL DEFAULT 'free'
    CHECK (tipo_periodo IN ('free', 'mensal', 'trimestral', 'semestral', 'anual')),
  link_checkout       TEXT NOT NULL DEFAULT '',       -- URL do gateway de pagamento
  recursos            JSONB NOT NULL DEFAULT '[]',    -- Array de strings exibidas no card de plano
  ativo               BOOLEAN NOT NULL DEFAULT true,
  destaque            BOOLEAN NOT NULL DEFAULT false, -- Destaque visual na página de preços
  ordem_exibicao      INTEGER NOT NULL DEFAULT 1
    CHECK (ordem_exibicao > 0),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed inicial: planos Free e Pro
INSERT INTO public.planos_sistema (slug, nome, descricao, valor, tipo_periodo, link_checkout, recursos, destaque, ordem_exibicao)
VALUES
  (
    'free',
    'Gratuito',
    'Para começar a explorar a plataforma',
    0,
    'free',
    '',
    '["1 grupo de disparo","2 marketplaces","10 disparos por dia","1 destino por grupo"]',
    false,
    1
  ),
  (
    'pro',
    'Pro',
    'Para afiliados que querem escalar resultados',
    97.00,
    'mensal',
    '',   -- preencher com link do gateway quando definido
    '["Grupos ilimitados","4 marketplaces","Disparos ilimitados","Múltiplos destinos por grupo","Suporte prioritário"]',
    true,
    2
  );

-- Índice para listagem pública (só planos ativos, ordenados)
CREATE INDEX idx_planos_sistema_ativos ON public.planos_sistema (ordem_exibicao) WHERE ativo = true;

-- RLS: leitura pública (página de preços), escrita apenas admin via supabase_admin
ALTER TABLE public.planos_sistema ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Planos visíveis por todos" ON public.planos_sistema
  FOR SELECT USING (true);

-- Sem INSERT/UPDATE/DELETE policy para usuários comuns — só via supabaseAdmin (service_role)
